name: Build .NET MAUI Windows

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install Workloads
        run: dotnet workload install maui

      - name: Build for Windows
        run: dotnet publish -c Release -f net9.0-windows10.0.19041.0 -r win-x64 --self-contained true -p:WindowsPackageType=MSIX -o ./publish
        
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: ./publish